services:
  postgres:    
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1123QwER
      POSTGRES_USER: postgres
      POSTGRES_DB: budget_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  budget-web:
    image: budget-web
    restart: always
    ports:
      - "8080:8000"
    depends_on:
      - postgres
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      SECRET_KEY: 'pft%$g(z2=9!w8z&yuiehrfrjwhxv6oj6^!96w-dq(v#2x-$ih'
      APP_ENVIRONMENT: 'development'
      ALLOWED_HOSTS: '*'
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASS: 1123QwER
      DB_NAME: budget_db
    