version: '3.7'
services:
  postgres:
    env_file:
        - .env
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
  budget-web:
    env_file:
        - .env
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    entrypoint: ["sh", "-c", "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      APP_ENVIRONMENT: ${APP_ENVIRONMENT}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DB_HOST: postgres
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DEBUG: True
  pgadmin:
    image: dpage/pgadmin4
    env_file:
    - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
      PGADMIN_CONNECTION_HOST: ${PGADMIN_CONNECTION_HOST}
      PGADMIN_CONNECTION_PORT: ${PGADMIN_CONNECTION_PORT}
    ports:
      - 8080:${PGADMIN_LISTEN_PORT}
    depends_on:
      - postgres
    links:
      - postgres
volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOST_PATH_TO_POSTGRES_DATA_DIR}

