# Generated by Django 4.0.4 on 2022-04-12 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_budget_value_alter_expense_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='name',
        ),
    ]
